"""
GitHub PR opener — creates a branch, commits deletions, opens a PR.
Requires GITHUB_TOKEN environment variable.
"""
import os
import subprocess
from datetime import datetime
from dataclasses import dataclass


@dataclass
class PRResult:
    success: bool
    pr_url: str | None
    branch_name: str
    message: str


def _run(cmd: list[str], cwd: str) -> tuple[int, str]:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return result.returncode, (result.stdout + result.stderr).strip()


def get_default_branch(project_path: str) -> str:
    code, out = _run(["git", "symbolic-ref", "refs/remotes/origin/HEAD"], project_path)
    if code == 0 and "/" in out:
        return out.split("/")[-1].strip()
    return "main"


def create_cleanup_branch(project_path: str) -> str:
    date_str = datetime.now().strftime("%Y-%m-%d")
    branch_name = f"deadcode/cleanup-{date_str}"

    # Check if branch exists, add suffix if so
    code, _ = _run(["git", "rev-parse", "--verify", branch_name], project_path)
    if code == 0:
        branch_name = f"{branch_name}-{datetime.now().strftime('%H%M')}"

    _run(["git", "checkout", "-b", branch_name], project_path)
    return branch_name


def commit_deletions(project_path: str, deleted_functions: list[dict]) -> bool:
    """Stage all modified files and commit."""
    _run(["git", "add", "-A"], project_path)

    # Build commit message
    names = [f["name"] for f in deleted_functions[:10]]
    extra = len(deleted_functions) - 10
    summary = ", ".join(names)
    if extra > 0:
        summary += f" and {extra} more"

    message = f"chore: remove {len(deleted_functions)} dead functions\n\n"
    message += "Removed by Dead Code Archaeologist — functions with no callers\n"
    message += "and no git activity for extended periods.\n\n"
    message += "Functions removed:\n"
    for fn in deleted_functions:
        message += f"  - {fn['name']} ({fn['file']}:{fn['line']})\n"
    message += "\nAll existing tests passed after removal."

    code, out = _run(["git", "commit", "-m", message], project_path)
    return code == 0


def push_branch(project_path: str, branch_name: str) -> bool:
    code, _ = _run(["git", "push", "-u", "origin", branch_name], project_path)
    return code == 0


def open_pr(project_path: str, branch_name: str, deleted_functions: list[dict]) -> PRResult:
    """Open a GitHub PR using the gh CLI."""
    default_branch = get_default_branch(project_path)

    title = f"chore: remove {len(deleted_functions)} dead code functions"

    body = "## Dead Code Cleanup\n\n"
    body += "This PR was automatically generated by **Dead Code Archaeologist**.\n\n"
    body += "### What was removed\n\n"
    body += f"**{len(deleted_functions)} functions** with:\n"
    body += "- Zero callers found across the codebase\n"
    body += "- No git activity for an extended period\n"
    body += "- High confidence score from multi-signal analysis\n\n"
    body += "### Functions removed\n\n"
    body += "| Function | File | Confidence |\n"
    body += "|----------|------|------------|\n"
    for fn in deleted_functions[:30]:
        body += f"| `{fn['name']}` | `{fn['file']}:{fn['line']}` | {fn['confidence']}% |\n"
    if len(deleted_functions) > 30:
        body += f"\n_...and {len(deleted_functions) - 30} more_\n"
    body += "\n### Safety\n\n"
    body += "✅ All existing tests passed after removal.\n"
    body += "🔀 Easy to revert: `git revert` any commit in this PR.\n"

    code, out = _run([
        "gh", "pr", "create",
        "--title", title,
        "--body", body,
        "--base", default_branch,
        "--head", branch_name,
    ], project_path)

    if code == 0:
        # extract PR URL from output
        pr_url = out.strip().split("\n")[-1]
        return PRResult(success=True, pr_url=pr_url, branch_name=branch_name, message="PR created!")
    else:
        return PRResult(success=False, pr_url=None, branch_name=branch_name, message=out)
